edition = "2021"
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Max"
combine_control_flow_expr = true
indent_style = "Block"
match_block_trailing_comma = true
max_width = 100
use_field_init_shorthand = true
use_try_shorthand = true
